export const movies =[
    {
        "_id":"123",
        "name":"Movie1",
        "image":"https://th.bing.com/th/id/OIP.Du7TzcTWbAXk6VrZJILt1AHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.5",
        "cast":["sai","vignan","reddy"]
    },
  {
        "_id":"124",
        "name":"Movie2",
        "image":"https://th.bing.com/th/id/OIP.sJbI8ErPsALjgfEo2Iq7QAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.6",
        "cast":["sai","vignan","reddy"]
    },
   {
        "_id":"125",
        "name":"Movie3",
        "image":"https://th.bing.com/th/id/OIP.uh0WeM74sZG3LaAAuk15vAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.7",
        "cast":["sai","vignan","reddy"]
    },
    {
        "_id":"126",
        "name":"Movie1",
        "image":"https://th.bing.com/th/id/OIP.Du7TzcTWbAXk6VrZJILt1AHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.5",
        "cast":["sai","vignan","reddy"]
    },
  {
        "_id":"127",
        "name":"Movie2",
        "image":"https://th.bing.com/th/id/OIP.sJbI8ErPsALjgfEo2Iq7QAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.6",
        "cast":["sai","vignan","reddy"]
    },
   {
        "_id":"128",
        "name":"Movie3",
        "image":"https://th.bing.com/th/id/OIP.uh0WeM74sZG3LaAAuk15vAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.7",
        "cast":["sai","vignan","reddy"]
    },
    {
        "_id":"129",
        "name":"Movie1",
        "image":"https://th.bing.com/th/id/OIP.Du7TzcTWbAXk6VrZJILt1AHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.5",
        "cast":["sai","vignan","reddy"]
    },
  {
        "_id":"130",
        "name":"Movie2",
        "image":"https://th.bing.com/th/id/OIP.sJbI8ErPsALjgfEo2Iq7QAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.6",
        "cast":["sai","vignan","reddy"]
    },
   {
        "_id":"131",
        "name":"Movie3",
        "image":"https://th.bing.com/th/id/OIP.uh0WeM74sZG3LaAAuk15vAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.7",
        "cast":["sai","vignan","reddy"]
    },
    {
        "_id":"132",
        "name":"Movie1",
        "image":"https://th.bing.com/th/id/OIP.Du7TzcTWbAXk6VrZJILt1AHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.5",
        "cast":["sai","vignan","reddy"]
    },
  {
        "_id":"133",
        "name":"Movie2",
        "image":"https://th.bing.com/th/id/OIP.sJbI8ErPsALjgfEo2Iq7QAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.6",
        "cast":["sai","vignan","reddy"]
    },
   {
        "_id":"134",
        "name":"Movie3",
        "image":"https://th.bing.com/th/id/OIP.uh0WeM74sZG3LaAAuk15vAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7",
        "rating":"4.7",
        "cast":["sai","vignan","reddy"]
    }
]